### ISSUE TITLE
Trash code

### ISSUE THREAD

**Issue by Burrit0z** [Burrit0z/kai#2]
Pls remove trash code from the start of this project

**Comment by iCrazeiOS** [comment]
this repo should be deleted until this issue is resolved.

**Comment by Burrit0z** [comment]
True

Carson
________________________________

**Comment by Burrit0z** [comment]
> this repo should be deleted until this issue is resolved.

ok fixed shit code and made it cursed instead (not using layoutStackView tho xD), cba to rewrite this project completely since it was from May.
